local builtin = require('telescope.builtin')
local themes = require('telescope.themes')

vim.keymap.set('n', '<leader>f', function()
	builtin.find_files(themes.get_dropdown()) end, {}) 
vim.keymap.set('n',	'<leader>gf', function()
	builtin.git_files(themes.get_dropdown()) end, {})
vim.keymap.set('n', '<leader><leader>', builtin.buffers, {})
vim.keymap.set('n', 'z=', builtin.spell_suggest, {})
vim.keymap.set('n', '<leader>gd', function()
	builtin.lsp_references(themes.get_dropdown()) end, {})
vim.keymap.set('n', '<leader>gi', function()
	builtin.lsp_implementations(themes.get_dropdown()) end, {})
vim.keymap.set('n', '<leader>gD', function()
	builtin.lsp_dynamic_workspace_symbols(themes.get_dropdown()) end, {})
